#!/usr/sbin/nft -f
table ip discrete_filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iifname "lo" counter accept
        ct state established,related counter accept
        ct state invalid counter drop
        ip protocol icmp counter accept
        tcp dport 22822 counter accept comment "SSH key-only"
        tcp dport 80 counter accept comment "HTTP ACME and HTTPS redirect only"
        tcp dport 443 counter accept comment "Pay HTTPS edge"
        counter drop
    }
    chain forward {
        type filter hook forward priority 0; policy drop;
    }
    chain output {
        type filter hook output priority 0; policy accept;
    }
}
