#!/usr/sbin/nft -f

table inet discrete_filter {
    chain input {
        type filter hook input priority 0;
        policy drop;

        iifname "lo" counter accept

        ct state established,related counter accept
        ct state invalid counter drop

        meta l4proto icmp counter accept
        meta l4proto ipv6-icmp counter accept

        tcp dport 22822 counter accept comment "SSH"
        tcp dport 9330 counter accept comment "Discrete P2P"
        tcp dport 9331 counter accept comment "Discrete RPC HTTP"
        tcp dport 9332 counter accept comment "Discrete RPC HTTPS"

        counter drop
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}
